<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 700px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 25px;
            text-align: center;
        }
        .header h2 {
            margin: 0;
            font-size: 24px;
        }
        .summary-cards {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }
        .summary-card {
            background-color: #f8f9fa;
            border-left: 4px solid #667eea;
            padding: 15px;
            border-radius: 5px;
        }
        .summary-card h3 {
            margin: 0 0 5px 0;
            font-size: 14px;
            color: #666;
            text-transform: uppercase;
        }
        .summary-card p {
            margin: 0;
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        .orders-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        .orders-table thead {
            background-color: #667eea;
            color: white;
        }
        .orders-table th {
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }
        .orders-table td {
            padding: 12px;
            border-bottom: 1px solid #e9ecef;
        }
        .orders-table tbody tr:hover {
            background-color: #f8f9fa;
        }
        .no-orders {
            background-color: #fff3cd;
            border: 1px solid #ffeaa7;
            border-radius: 5px;
            padding: 20px;
            text-align: center;
            color: #856404;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #e9ecef;
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>📊 Daily Sales Report</h2>
        <p style="margin: 5px 0 0 0; font-size: 14px;">{{ \Carbon\Carbon::now()->format('l, F j, Y') }}</p>
    </div>

    <p>Hello Admin,</p>
    <p>Here is your daily sales summary for today:</p>

    <div class="summary-cards">
        <div class="summary-card">
            <h3>Total Orders</h3>
            <p>{{ count($orders) }}</p>
        </div>
        <div class="summary-card">
            <h3>Items Sold</h3>
            <p>{{ $totalItemsSold }}</p>
        </div>
        <div class="summary-card">
            <h3>Revenue</h3>
            <p>${{ number_format($totalRevenue, 2) }}</p>
        </div>
    </div>

    @if(count($orders) > 0)
        <h3>Order Details</h3>
        <table class="orders-table">
            <thead>
                <tr>
                    <th>Order #</th>
                    <th>Customer</th>
                    <th>Items</th>
                    <th>Total</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $order)
                    <tr>
                        <td>#{{ $order->id }}</td>
                        <td>{{ $order->user->name }}</td>
                        <td>{{ $order->items->sum('quantity') }} item(s)</td>
                        <td>${{ number_format($order->total_amount, 2) }}</td>
                        <td>{{ $order->created_at->format('g:i A') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-orders">
            <strong>No orders were placed today.</strong>
            <p style="margin: 10px 0 0 0;">Check back tomorrow for your daily sales report.</p>
        </div>
    @endif

    <div class="footer">
        <p>This is an automated daily report generated by {{ config('app.name') }}.</p>
        <p style="margin: 5px 0 0 0;">Report generated at {{ \Carbon\Carbon::now()->format('g:i A') }}</p>
    </div>
</body>
</html>
